# Generated by Django 3.1.2 on 2020-10-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
